

services:
  discovery-service:
    build: ./discovery-service  # Đảm bảo build từ thư mục chứa Discovery Service
    ports:
      - "8761:8761"  # Mở cổng 8761 cho Eureka Server
    environment:
      - SPRING_APPLICATION_NAME=discovery-service  # Đặt tên ứng dụng
      - SERVER_PORT=8761  # Đặt cổng cho Eureka Server
    networks:
      - microservices-network
      
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - order-service
      - customer-service
    networks:
      - microservices-network

  product-service:
    build: ./product-service
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=product-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=productdb
    depends_on:
      - product-db
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=order-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=orderdb
    depends_on:
      - order-db
    networks:
      - microservices-network

  customer-service:
    build: ./customer-service
    ports:
      - "8083:8080"
    environment:
      - DB_HOST=customer-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=customerdb
    depends_on:
      - customer-db
    networks:
      - microservices-network

  product-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: productdb
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  order-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: orderdb
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  customer-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: customerdb
    volumes:
      - customer-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  product-db-data:
  order-db-data:
  customer-db-data:
